### PR TITLE
[Needs Review] feature/vcurrency-items

### PR DESCRIPTION
**Pull request by elmigranto**
#3

### CODE REVIEW

**Comment by elmigranto** [comment]
Okay, I finally sorted everything out on my end, will try to catch up with work ASAP!
Sorry for delaying this :(

**Comment by elmigranto** [comment]
Basics are in place, except paging, things to add:

- [ ] paging
- [ ] load currency list so we can give nicer way to specify costs other than typing things like `riot_points` all the time (typos will make it through creating new currency) 
- [ ] proxy requests in a way that sends errors back (e.g. upstream replies with 400, but client gets 200 atm); 
- [ ] make UI better.

Am I missing something?

**Comment by j3k0** [comment]
* No need for paging. There won't be hundreds of products.
 * I suggest the list of known currencies to be specified in a environment variable
    * `CURRENCY_CODES="riot_points,silver_coins"`
 * I didn't test the UI, but it's fine to be minimalist, it's just internal stuff.

**Comment by elmigranto** [comment]
This one is ready for feedback.

> paging

Using `{limit: 500}` for now (max allowed by vcurrency).

> load currency list

Via env var — `process.env.VIRTUAL_CURRENCY_CURRENCY_CODES.split(',')` returned alongside with items list.

> proxy requests in a way that sends errors back (e.g. upstream replies with 400, but client gets 200 atm);

Fixed.

> make UI better.

Pretty much ignored except swal for error messages / prompts. Some issues:

  - multiple currencies allows (e.g. specifying amount in gold twice, perhaps check this on vcurrecny side too);
  - allows adding a new currency to the "full list" (every possible one is already there);
  - some junky layout.

**Comment by elmigranto** [comment]
> 	Hide all UI things except login and item list

**Comment by elmigranto** [comment]
Merging into `dev` for now, take a look when you have time.

**Pull request merged**
