### PR TITLE
User lookup by alias

### PR DESCRIPTION
**Pull request by elmigranto**
Ref #40.

### CODE REVIEW

**Comment by elmigranto** [comment]
Tried to test it, can't run anything Erlang: OpenSSL was replaced with BoringSSL in macOS 10.13, linking fails: no couch -> no vcurrecny -> client XHR fails.

Tried to run against public production URLs, but for some reason CF rejects requests from node, while Chrome opens things just fine. For example, product list from vcurrency (will send URL in telegram).

Digging into places to change behaviour and find a workaround, but maybe you can try it on your machine if you haven't upgraded. The thing to test is whether look up by alias works and if UI reacts well in case stuff you enter in search field (tag) is not exactly what you get from admin API (e.g.: search by tag, get different username, try to ban/unban user).

**Comment by j3k0** [comment]
Hi @elmigranto, will you be able to finish this one quickly?

**Comment by elmigranto** [comment]
When searching, will look for exact user id and tag alias. In case we have single result or both resolve to same user id, loads profile while going to `<web>/users/:userId` page. That page now requires single exact match on user ID, though, so `<web>/users/elmigrant0` won't work, but `<web>/users/elmigranto` will (does not accept aliases). 

screenshot 2017-10-20 16 59 47

Should not really happen, but if alias lookup and user id search resolve to different User IDs, will ask to search for one of those.

**Comment by elmigranto** [comment]
Note! Accidentally, configuring directory service is now required for admin module. Do we need to refactor so it doesn't? @j3k0

**Comment by elmigranto** [comment]
On the bright side, we will know for sure whether user exists or not :)

**Comment by j3k0** [comment]
It's ok to have `ganomede-directory` as a direct dependency. When we're bored, some day, we can refactor. But we're not bored right now, are we? ;-)

Mainly because `ganomede-users` already gives access to aliases as "virtual" metadata (using the .../usermeta/... endpoint, which could be compatible with potential other account backends, and not only `ganomede-directory`). Right now, we don't need that.

**Comment by elmigranto** [comment]
Ok, got it. But to clarify, it’s **required** now, not just direct. So if there are no env vars for it, **user profiles will not load**.

**Comment by j3k0** [comment]
Crystal clear. It's ok.

**Pull request merged**
