### PR TITLE
better data ui and batch upload

### PR DESCRIPTION
**Pull request by elmigranto**
I've been wondering if it would be better to implement actual batch upload endpoint inside `data` service (as opposed to uploading docs one by one), so it can be transactional which is kind of required if we are going to insert interdependent documents.

### CODE REVIEW

**Comment by j3k0** [comment]
Sure, let's add a batch edit/create endpoint (the thing to consider is, what happens when in the batch there is a mix of new and updated documents), I think it should just do "create_or_update"

**Comment by j3k0** [comment]
Hey @elmigranto 

There's a little issue with CSV import. Columns do have to be the same size. See below:

**Test CSV:**

```csv
fr:animaux,en:animals,es:ciudades
Chien,Dog,Madrid
Chat,Cat,Barcelona
,Dragon,Mexico
,,Lima
```

**Expected result:**

```
About to create 3 documents with 2,3,4 items.

fr:animaux    en:animals    es:ciudades
Chien         Dog           Madrid
Chat	      Cat           Barcelona
              Dragon        Mexico
                            Lima
```

**Actual result:**

```
About to create 3 documents with 2 items each.

fr:animaux    en:animals    es:ciudades
Chien         Dog           Madrid
Chat	      Cat           Barcelona
```

**Comment by j3k0** [comment]
(not really a bug, label as such because it's urgent!)

**Comment by elmigranto** [comment]
Okay, should be fixed now.

**Comment by j3k0** [comment]
It works, good job!

**Pull request merged**
