### PR TITLE
Fix dupes

### PR DESCRIPTION
**Pull request by elmigranto**
https://github.com/j3k0/ganomede-data/issues/4

So I changed code to accumulate CSV parsing errors/warnings and display them on UI. If errors are there, no import button appears. Resulting table contains stuff with errors "fixed" (same id columns are merged and duplicates removed).

Perhaps we want to add an ability to download that as CSV or import fixed version right away?

### CODE REVIEW

**Comment by j3k0** [comment]
Yes allowing to import anyway, but knowing the errors and what the importer did to resolve them, is great. This way we can still make sure to solve issues in the original files.

Let's put aside the option to download a "cleaned-up" CSV as an idea for later (except if that's a 5 minutes thing).

**Comment by j3k0** [comment]
Duplicated words appear as both Errors and Warnings, so it doesn't allow to import.

screen shot 2016-12-16 at 15 19 35

**Comment by elmigranto** [comment]
Weird, because duplicates always go to errors array, working on this. Could you please attach problematic CSV?

**Comment by elmigranto** [comment]
Okay, added: comprehensive warnings report and ability to save fixed version. 
screenshot 2016-12-19 17 05 12

**Comment by elmigranto** [comment]
Maybe we want to also filter (and fix if possible) words that do not match our criteria (certain length, uppercase ascii only)?

**Comment by j3k0** [comment]
> Maybe we want to also filter (and fix if possible) words that do not match our criteria (certain length, uppercase ascii only)?

Let's keep this CSV import use-case agnostic. Maybe we can add a way to define app-specific import validators... Enhancement idea for later.

**Comment by j3k0** [comment]
@elmigranto you can fix circleci and merge this PR. it's deployed and works fine.

**Comment by elmigranto** [comment]
Okay, for some reason CI goes to actual servers. Some of them local, some prod, switched to all prod, so instead of "connection refused" we are getting 503 for some reason (probably private request, though `https://***/directory/v1/about` is 503 too, huh?).

Anyways, I fixed syntax errors with correct node version for CI (6.x), will be upgrading to 8 and rewriting tests after I figure out other issues.

**Pull request merged**
